language: java
jdk:
  - openjdk8

script:
- mvn clean install
cache:
  directories:
    - '$HOME/.m2/repository'

jobs:
  include:
    - stage: deploy
      deploy:
        provider: heroku
        api_key: ${HEROKU_API_KEY}
        app: bibliotheque-ocr